"""tokens

Revision ID: 177ab8c57dc6
Revises: dc9eae1a71f9
Create Date: 2020-03-16 15:09:48.818915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '177ab8c57dc6'
down_revision = 'dc9eae1a71f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'refresh_tokens',
        sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('expiration_date', mysql.DATETIME(), nullable=False),
        sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='refresh_tokens_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'access_tokens',
        sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('expiration_date', mysql.DATETIME(), nullable=False),
        sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
        sa.Column('refresh_token_id', mysql.VARCHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(['refresh_token_id'], ['refresh_tokens.id'], name='access_tokens_ibfk_2'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='access_tokens_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
